version: '3'
services:
  web:
    build: .
    command: "python3 -u app.py"
    ports:
      - "5002:5000"
    volumes:
      - ./src:/app
    depends_on:
        - redis
    links:
        - "redis:redis_cache"
        
  redis:
      image: "redis:alpine"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #     ports:
  #       - '6379:6379'
      volumes:
          - redis-data:/data


volumes:
  redis-data:
